// Generated by CoffeeScript 1.4.0
var tmpl;

tmpl = function(it) {
  var generate, isArr, isObj, isStr, log, parse, wrap;
  isArr = Array.isArray;
  isObj = function(it) {
    var rule1, rule2;
    rule1 = typeof it("object");
    rule2 = isArr(it);
    return rule1 && (!rule2);
  };
  isStr = function(it) {
    return typeof it === "string";
  };
  log = function() {
    var _ref;
    return typeof console !== "undefined" && console !== null ? (_ref = console.log) != null ? typeof _ref.apply === "function" ? _ref.apply(console, arguments) : void 0 : void 0 : void 0;
  };
  parse = function(it) {
    var attr, clas, head, id, name, res;
    res = it.match(/(^\S+)(\s.*)?$/).slice(0, 3);
    head = res[1];
    attr = res[2] || '';
    name = head.match(/^\w[\w\d-_]*/);
    if (name != null) {
      name = name[0];
    } else {
      name = "div";
    }
    id = head.match(/#\w[\w\d-_]*/);
    if (id != null) {
      id = id[0].slice(1);
    } else {
      id = '';
    }
    clas = head.match(/\.\w[\w\d-_]*/g);
    if (clas == null) {
      clas = [];
    }
    clas = clas.map(function(item) {
      return item.slice(1);
    }).join(" ");
    return [name, id, clas, attr];
  };
  wrap = function(them, child) {
    var attr, clas, clas_attr, id, id_attr, name;
    name = them[0], id = them[1], clas = them[2], attr = them[3];
    if (!isStr(child)) {
      child = generate(child);
    }
    clas_attr = clas.length > 0 ? "class='" + clas + "'" : '';
    id_attr = id.length > 0 ? "id='" + id + "'" : '';
    return "<" + name + " " + clas_attr + " " + id_attr + " " + attr + ">" + child + "</" + name + ">";
  };
  generate = function(it) {
    var html, key, value;
    log("generate", it);
    if (isArr(it)) {
      return it.map(generate);
    } else if (typeof it === "object") {
      html = '';
      for (key in it) {
        value = it[key];
        html += wrap(parse(key), value);
      }
      return html;
    } else if (isStr(it)) {
      return wrap(parse(it), '');
    }
  };
  return generate(it);
};

if (typeof exports !== "undefined" && exports !== null) {
  exports.tmpl = tmpl;
}
